import {Component,OnInit} from '@angular/core';import {CommonModule} from '@angular/common';import {FormsModule} from '@angular/forms';import {Router,RouterLink} from '@angular/router';import {Aluno,Pagina,StatusAluno} from '../../models/aluno.model';import {AlunoService} from '../../core/services/aluno.service';import {AuthService} from '../../core/auth/auth.service';
// lista os dados que chegam do backend
@Component({selector:'app-lista-alunos',standalone:true,imports:[CommonModule,FormsModule,RouterLink],template:`<header><div><strong>Start Students</strong><span>Gestão de alunos</span></div><button class="secundario" (click)="sair()">Sair</button></header><main><div class="topo"><div><h1>Alunos</h1><p>Consulte e gerencie os alunos cadastrados.</p></div><a *ngIf="admin" routerLink="/alunos/novo" class="botao">Novo aluno</a></div><section class="filtros"><input placeholder="Buscar por nome" [(ngModel)]="nome" (keyup.enter)="carregar(0)"><input placeholder="Matrícula" [(ngModel)]="matricula" (keyup.enter)="carregar(0)"><select [(ngModel)]="status"><option value="">Todos os status</option><option value="ATIVO">Ativo</option><option value="INATIVO">Inativo</option></select><button (click)="carregar(0)">Buscar</button></section><div class="estado" *ngIf="carregando">Carregando alunos...</div><div class="estado erro" *ngIf="erro">{{erro}} <button (click)="carregar(pagina)">Tentar novamente</button></div><div class="estado" *ngIf="!carregando&&!erro&&dados?.content?.length===0">Nenhum aluno encontrado com esses filtros.</div><div class="tabela" *ngIf="!carregando&&!erro&&dados?.content?.length"><table><thead><tr><th>Nome</th><th>Matrícula</th><th>Status</th><th>Ações</th></tr></thead><tbody><tr *ngFor="let a of dados?.content"><td>{{a.nomeCompleto}}</td><td>{{a.matricula}}</td><td><span class="tag">{{a.status}}</span></td><td><a [routerLink]="['/alunos',a.id]">Ver</a><a *ngIf="admin" [routerLink]="['/alunos',a.id,'editar']">Editar</a><button class="link perigo" *ngIf="admin" (click)="excluir(a)">Excluir</button></td></tr></tbody></table></div><nav *ngIf="dados&&dados.totalPages>1"><button [disabled]="pagina===0" (click)="carregar(pagina-1)">Anterior</button><span>Página {{pagina+1}} de {{dados.totalPages}}</span><button [disabled]="pagina+1>=dados.totalPages" (click)="carregar(pagina+1)">Próxima</button></nav></main>`})
export class ListaAlunosComponent implements OnInit{
 dados?:Pagina<Aluno>;nome='';matricula='';status:''|StatusAluno='';pagina=0;carregando=false;erro='';admin=false;
 constructor(private alunos:AlunoService,private auth:AuthService,private router:Router){}
 ngOnInit(){this.admin=this.auth.administrador();this.carregar(0)}
 carregar(p:number){
  // cada busca vai para a API com os filtros e a pagina atual
  this.pagina=p;this.carregando=true;this.erro='';
  this.alunos.listar({nome:this.nome,matricula:this.matricula,status:this.status,page:p}).subscribe({next:d=>{this.dados=d;this.carregando=false},error:()=>{this.erro='Não foi possível carregar os alunos.';this.carregando=false}})
 }
 excluir(a:Aluno){
  // confirma antes de fazer a exclusao logica
  if(confirm('Excluir '+a.nomeCompleto+'? Essa ação vai inativar o cadastro.'))this.alunos.excluir(a.id).subscribe({next:()=>this.carregar(this.pagina),error:e=>this.erro=e.status===403?'Você não tem permissão para esta ação.':'Não foi possível excluir.'})
 }
 sair(){this.auth.logout();this.router.navigate(['/login'])}
}